variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE

stages:
    - deploy
    - status
    # - test

build:
    image: python:3.6
    stage: deploy
    before_script:
        - python3 -m pip install -U setuptools wheel twine
    script:
        - FAIL=0
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/*.tar.gz || FAIL=1
        - twine upload dist/*.whl || FAIL=1
    after_script:
        - python3 -m pip install -U anybadge
        - if [$FAIL -eq 0]; then anybadge --label=pipeline --value=passing --file=build.svg passing=green failing=red; else anybadge --label=pipeline --value=failing --file=build.svg passing=green failing=red; fi
        - mkdir public; mv build.svg public/build.svg
    artifacts:
        paths:
            - build/
            - dist/
            - cfd_reader.egg-info/
    only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    - /^\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    environment:
        name: dev

pages:
    stage: status
    dependencies:
        - build
    script:
        - echo
    artifacts:
        paths:
            - public/
    only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    - /^\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
# test:
#     image: python:3.6
#     stage: test
#     #before_script:
#     #    - python3 -m pip install -U setuptools wheel twine
#     script:
#         - mkdir ~/.cfd-faces && cd ~/.cfd-faces && mkdir images
#         - touch data.csv images.pickle
#         - python3 -m pip install cfd-reader
#         - python3 -c "import cfd_reader"
#     only:
#     - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
#     - /^\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
#     - /^\d+\.\d+\.\d+\.\d+([abc]\d*)?$/ # Developmental tag
#     environment:
#         name: dev
